// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTxykvK3sSnfMrL5oyUy9_cz6XEAibIqg',
    appId: '1:266784401738:web:6e325399ff7c0830d539b3',
    messagingSenderId: '266784401738',
    projectId: 'flutter-ui-salait-project',
    authDomain: 'flutter-ui-salait-project.firebaseapp.com',
    storageBucket: 'flutter-ui-salait-project.firebasestorage.app',
    measurementId: 'G-7QJK82L73B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbFKIR-JvMhIijDihjfym4PaONw11o2NM',
    appId: '1:266784401738:android:b96b6deae32083d2d539b3',
    messagingSenderId: '266784401738',
    projectId: 'flutter-ui-salait-project',
    storageBucket: 'flutter-ui-salait-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5-rUqm6ylslVF0dubocQbc6d-LAy30dw',
    appId: '1:266784401738:ios:7c6200d4b6c7a86ed539b3',
    messagingSenderId: '266784401738',
    projectId: 'flutter-ui-salait-project',
    storageBucket: 'flutter-ui-salait-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiProjectSalait',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5-rUqm6ylslVF0dubocQbc6d-LAy30dw',
    appId: '1:266784401738:ios:7c6200d4b6c7a86ed539b3',
    messagingSenderId: '266784401738',
    projectId: 'flutter-ui-salait-project',
    storageBucket: 'flutter-ui-salait-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiProjectSalait',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTxykvK3sSnfMrL5oyUy9_cz6XEAibIqg',
    appId: '1:266784401738:web:d15e081cfea8c308d539b3',
    messagingSenderId: '266784401738',
    projectId: 'flutter-ui-salait-project',
    authDomain: 'flutter-ui-salait-project.firebaseapp.com',
    storageBucket: 'flutter-ui-salait-project.firebasestorage.app',
    measurementId: 'G-XG76NJWR7M',
  );
}
